name: tem_doacao_mobile
description: An app used to donate things.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  built_collection: 4.3.2
  cupertino_icons: 0.1.2
  dartz: 0.8.9
  dio: 3.0.7
  equatable: 1.1.0
  flutter_bloc: 2.1.1
  font_awesome_flutter: 8.5.0
  google_sign_in: 4.1.1
  get_it: 3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 4.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - config/
